server:
  interface: 127.0.0.1@8053
  aggressive-nsec: yes
  do-daemonize: yes
  access-control: 127.0.0.1/32 allow
  username: unbound
  verbosity: 2
  log-time-ascii: yes
  log-servfail: yes
remote-control:
  control-enable: no
