apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager-k8s-01
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: gcr.io/google-containers/kube-controller-manager:v1.18.5
    ports:
    - name: https
      containerPort: 10257
      protocol: TCP
    command:
    - /usr/local/bin/kube-controller-manager
    args:
    - --cluster-name=tblflp
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller.kubeconfig
    - --authorization-kubeconfig=/etc/kubernetes/controller.kubeconfig
    - --bind-address=10.199.15.1
    - --cluster-cidr=10.196.0.0/16
    - --service-cluster-ip-range=10.195.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller.kubeconfig
    - --service-account-private-key-file=/etc/kubernetes/pki/server.key
    - --use-service-account-credentials=true
    - --feature-gates=DynamicAuditing=true,HPAScaleToZero=true
    - --tls-cert-file=/etc/kubernetes/pki/server.crt
    - --tls-private-key-file=/etc/kubernetes/pki/server.key
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: config
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
      name: volume-plugins
  volumes:
  - name: config
    hostPath:
      path: /etc/kubernetes
  - name: volume-plugins
    hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
